############################################### CHANGE HERE ####################################################################
squat_config: 'g1_squat.yaml'
loco_config: 'g1_loco.yaml'
exp_name: 'run_teleoperation'
xml_path: "resources/robots/g1_description/g1_29dof_camera.xml"

control_dt: 0.02
control_decimation: 4

msg_type: "hg"
imu_type: "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"
################################################################################################################################

num_actions: 0
num_obs: 0
num_dof: 29
dof_idx: [ # change with num_dof
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
  12, 13, 14,
  15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28
]
action_hl_idx: [ # change with num_actions
  15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28
]

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5,
                      6, 7, 8, 9, 10, 11]
arm_waist_joint2motor_idx: [12, 13, 14,
                            15, 16, 17, 18, 19, 20, 21,
                            22, 23, 24, 25, 26, 27, 28]

kps: [ # change with urdf
  100, 100, 100, 150, 40, 40,
  100, 100, 100, 150, 40, 40,
  300, 300, 300,
  100, 100, 50, 50, 20, 20, 20,
  100, 100, 50, 50, 20, 20, 20
]
kds: [ # change with urdf
  2, 2, 2, 4, 2, 2,
  2, 2, 2, 4, 2, 2,
  3, 3, 3,
  2, 2, 2, 2, 1, 1, 1,
  2, 2, 2, 2, 1, 1, 1
]
default_angles: [ # change with urdf
   -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
   -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
   0, 0, 0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
]
